# Generated by Django 5.0.1 on 2026-02-11 21:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_igreja', models.CharField(blank=True, help_text='Igreja onde o usuário serve', max_length=200, null=True, verbose_name='Nome da Igreja')),
                ('cargo', models.CharField(blank=True, help_text='Ex: Líder de Jovens, Pastor, Coordenador', max_length=100, null=True, verbose_name='Cargo/Função')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('is_assinante', models.BooleanField(default=False, help_text='Usuário com acesso premium', verbose_name='É Assinante?')),
                ('data_inicio_assinatura', models.DateTimeField(blank=True, null=True, verbose_name='Data de Início da Assinatura')),
                ('data_fim_assinatura', models.DateTimeField(blank=True, null=True, verbose_name='Data de Fim da Assinatura')),
                ('stripe_customer_id', models.CharField(blank=True, help_text='ID do cliente no Stripe (para integração futura)', max_length=255, null=True, verbose_name='Stripe Customer ID')),
                ('stripe_subscription_id', models.CharField(blank=True, help_text='ID da assinatura no Stripe', max_length=255, null=True, verbose_name='Stripe Subscription ID')),
                ('receber_emails', models.BooleanField(default=True, help_text='Receber notificações e novidades por e-mail', verbose_name='Receber E-mails')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Perfil de Usuário',
                'verbose_name_plural': 'Perfis de Usuários',
            },
        ),
    ]
