# Generated by Django 5.0.1 on 2026-02-11 23:39

from django.db import migrations
import os


def setup_django_site(apps, schema_editor):
    """Cria ou atualiza o Site do Django para o django-allauth"""
    Site = apps.get_model('sites', 'Site')
    
    domain = os.environ.get('SITE_DOMAIN', 'dinamicas.onrender.com')
    site_name = os.environ.get('SITE_NAME', 'Dinâmicas para Igreja')
    
    # Criar ou atualizar o site com ID 1
    Site.objects.update_or_create(
        pk=1,
        defaults={
            'domain': domain,
            'name': site_name,
        }
    )


def reverse_setup(apps, schema_editor):
    """Função reversa (não faz nada, pois queremos manter o site)"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.RunPython(setup_django_site, reverse_setup),
    ]
