# Generated by Django 5.0.1 on 2026-02-11 21:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dinamica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Nome da dinâmica', max_length=200, verbose_name='Título')),
                ('numero', models.PositiveIntegerField(help_text='Número da dinâmica (1-120)', unique=True, verbose_name='Número')),
                ('categoria', models.CharField(choices=[('QUEBRA_GELO', 'Dinâmicas de Quebra-Gelo (1-20)'), ('AUTOCONHECIMENTO', 'Dinâmicas de Autoconhecimento (21-40)'), ('TRABALHO_EQUIPE', 'Dinâmicas de Trabalho em Equipe (41-60)'), ('ESPIRITUAIS', 'Dinâmicas Espirituais (61-80)'), ('DIVERSAO_ENERGIA', 'Dinâmicas de Diversão e Energia (81-100)'), ('PROFUNDAS', 'Dinâmicas Profundas para Momentos Marcantes (101-120)')], help_text='Categoria da dinâmica', max_length=20, verbose_name='Categoria')),
                ('descricao', models.TextField(help_text='Breve descrição da dinâmica', verbose_name='Descrição')),
                ('objetivo', models.TextField(help_text='Objetivo principal da dinâmica', verbose_name='Objetivo')),
                ('materiais', models.TextField(help_text='Lista de materiais necessários', verbose_name='Materiais Necessários')),
                ('passo_a_passo', models.TextField(help_text='Instruções detalhadas de execução', verbose_name='Passo a Passo')),
                ('tempo_estimado', models.CharField(help_text='Ex: 15-20 minutos', max_length=50, verbose_name='Tempo Estimado')),
                ('quantidade_participantes', models.CharField(help_text='Ex: 10-30 pessoas', max_length=50, verbose_name='Quantidade de Participantes')),
                ('nivel_intensidade', models.CharField(choices=[('BAIXO', 'Baixo'), ('MEDIO', 'Médio'), ('ALTO', 'Alto')], default='MEDIO', max_length=10, verbose_name='Nível de Intensidade')),
                ('publico_indicado', models.CharField(choices=[('TODOS', 'Todos os Públicos'), ('JOVENS', 'Jovens'), ('ADULTOS', 'Adultos'), ('CASAIS', 'Casais'), ('CRIANCAS', 'Crianças'), ('ADOLESCENTES', 'Adolescentes'), ('IDOSOS', 'Idosos'), ('LIDERANCA', 'Liderança')], default='TODOS', max_length=20, verbose_name='Público Indicado')),
                ('versiculo_base', models.CharField(blank=True, help_text='Versículo bíblico relacionado (opcional)', max_length=200, null=True, verbose_name='Versículo Base')),
                ('is_premium', models.BooleanField(default=False, help_text='Dinâmica disponível apenas para assinantes', verbose_name='É Premium?')),
                ('is_active', models.BooleanField(default=True, help_text='Dinâmica visível no sistema', verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('usuarios_favoritaram', models.ManyToManyField(blank=True, related_name='dinamicas_favoritas', to=settings.AUTH_USER_MODEL, verbose_name='Usuários que Favoritaram')),
            ],
            options={
                'verbose_name': 'Dinâmica',
                'verbose_name_plural': 'Dinâmicas',
                'ordering': ['numero'],
                'indexes': [models.Index(fields=['categoria'], name='dinamicas_d_categor_c940a0_idx'), models.Index(fields=['numero'], name='dinamicas_d_numero_83ba1b_idx'), models.Index(fields=['is_active'], name='dinamicas_d_is_acti_05cd88_idx')],
            },
        ),
    ]
